# Blog settings
permalink: /blog/:title


# My variables
name: Michał Daniel · software developer · Kraków
description: My personal website and what not.
author: Michał Daniel
copyright: Copyright Michał Daniel 2019+


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "CNAME", "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Site
url: https://morningbird.eu
